#!/usr/bin/env bash
# Keeps the server's copy of Cloudflare's IP ranges and origin-pull CA up to date (idempotent).
#
#   sudo bash infra/cloudflare/sync-ips.sh            # run once on VPS1 (or the single server)…
#   sudo bash infra/cloudflare/sync-ips.sh --install  # …and install a weekly systemd timer that re-runs it
#
# Writes to /etc/brookrege/cloudflare (override with CF_DIR):
#   ips-v4.txt, ips-v6.txt   used by the firewall (infra/provision/30-firewall.sh --cloudflare-only)
#   realip.conf              used by nginx: trusts CF-Connecting-IP only from these ranges
#   origin-pull-ca.pem       used by nginx when ORIGIN_PULL=on (Authenticated Origin Pulls)
# Then reloads nginx (after `nginx -t`) and re-applies the firewall, but only if something changed.
#
# Safety: a download that is empty, malformed or suspiciously short is rejected and the previous files
# are kept — a Cloudflare hiccup must never leave the site trusting nobody (or everybody).
set -euo pipefail

CF_DIR="${CF_DIR:-/etc/brookrege/cloudflare}"
CF_IPS_BASE="${CF_IPS_BASE:-https://www.cloudflare.com}"
CF_CA_URL="${CF_CA_URL:-https://developers.cloudflare.com/ssl/static/authenticated_origin_pull_ca.pem}"
SELF="$(readlink -f "$0")"

if [ "${1:-}" = "--install" ]; then
  [ "$(id -u)" -eq 0 ] || { echo "Run as root"; exit 1; }
  install -m 755 "$SELF" /usr/local/sbin/brookrege-cf-sync
  cat > /etc/systemd/system/brookrege-cf-sync.service <<'UNIT'
[Unit]
Description=Brookrege: refresh Cloudflare IP ranges and origin-pull CA
Wants=network-online.target
After=network-online.target docker.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/brookrege-cf-sync
UNIT
  cat > /etc/systemd/system/brookrege-cf-sync.timer <<'UNIT'
[Unit]
Description=Weekly refresh of Cloudflare IP ranges

[Timer]
OnCalendar=Mon *-*-* 03:17:00
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
UNIT
  systemctl daemon-reload
  systemctl enable --now brookrege-cf-sync.timer
  exec /usr/local/sbin/brookrege-cf-sync
fi

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
fetch() { curl -fsS --retry 3 --max-time 30 "$1" -o "$2"; }

V4_RE='^([0-9]{1,3}\.){3}[0-9]{1,3}/([89]|[12][0-9]|3[0-2])$'
V6_RE='^[0-9a-fA-F:]+:[0-9a-fA-F:]*/([0-9]{2,3})$'
validate() { # validate FILE REGEX MIN_COUNT LABEL
  local f="$1" re="$2" min="$3" label="$4"
  sed -i 's/\r$//; /^[[:space:]]*$/d' "$f"
  local bad; bad=$(grep -Evc "$re" "$f" || true)
  local n; n=$(wc -l < "$f")
  [ "$bad" = 0 ] || { echo "✗ $label: $bad malformed line(s) — keeping the previous list"; exit 1; }
  [ "$n" -ge "$min" ] || { echo "✗ $label: only $n ranges (expected ≥ $min) — keeping the previous list"; exit 1; }
  echo "  ✓ $label: $n ranges"
}

echo "▸ Downloading Cloudflare IP ranges"
fetch "$CF_IPS_BASE/ips-v4" "$TMP/ips-v4.txt"
fetch "$CF_IPS_BASE/ips-v6" "$TMP/ips-v6.txt"
validate "$TMP/ips-v4.txt" "$V4_RE" 10 "IPv4"
validate "$TMP/ips-v6.txt" "$V6_RE" 5 "IPv6"
sort -u -o "$TMP/ips-v4.txt" "$TMP/ips-v4.txt"
sort -u -o "$TMP/ips-v6.txt" "$TMP/ips-v6.txt"

{
  echo "# Generated by infra/cloudflare/sync-ips.sh on $(date -u +%Y-%m-%dT%H:%MZ) from $CF_IPS_BASE — do not edit."
  echo "# Only these ranges may tell nginx the visitor's real address (CF-Connecting-IP)."
  sed 's/.*/set_real_ip_from &;/' "$TMP/ips-v4.txt" "$TMP/ips-v6.txt"
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP/realip.conf"

echo "▸ Downloading the Authenticated Origin Pulls CA"
fetch "$CF_CA_URL" "$TMP/origin-pull-ca.pem"
openssl x509 -in "$TMP/origin-pull-ca.pem" -noout -checkend 2592000 >/dev/null \
  || { echo "✗ origin-pull CA is not a valid certificate (or expires within 30 days) — keeping the previous one"; exit 1; }
echo "  ✓ $(openssl x509 -in "$TMP/origin-pull-ca.pem" -noout -subject | sed 's/^subject=//'), valid until $(openssl x509 -in "$TMP/origin-pull-ca.pem" -noout -enddate | cut -d= -f2)"

install -d -m 755 "$CF_DIR"
changed=0
for f in ips-v4.txt ips-v6.txt origin-pull-ca.pem; do
  if ! cmp -s "$TMP/$f" "$CF_DIR/$f"; then install -m 644 "$TMP/$f" "$CF_DIR/$f"; changed=1; echo "  • updated $f"; fi
done
# realip.conf carries a timestamp, so compare it without the first line.
if ! cmp -s <(tail -n +2 "$TMP/realip.conf") <(tail -n +2 "$CF_DIR/realip.conf" 2>/dev/null || true); then
  install -m 644 "$TMP/realip.conf" "$CF_DIR/realip.conf"; changed=1; echo "  • updated realip.conf"
fi

if [ "$changed" = 0 ]; then echo "✓ Already up to date — nothing reloaded."; exit 0; fi

# Reload nginx only if its configuration still passes the test.
if command -v docker >/dev/null 2>&1; then
  for c in $(docker ps -q --filter label=com.docker.compose.service=nginx 2>/dev/null); do
    if docker exec "$c" nginx -t >/dev/null 2>&1; then docker exec "$c" nginx -s reload && echo "  ✓ nginx reloaded ($c)"
    else echo "✗ nginx -t failed in $c — NOT reloaded; the running config is unchanged. Details: docker exec $c nginx -t"; exit 1; fi
  done
fi
# Re-apply the firewall so the Cloudflare-only rules use the new ranges.
if [ -x /usr/local/sbin/brookrege-firewall ] && [ "${CF_SKIP_FIREWALL:-0}" != 1 ]; then
  /usr/local/sbin/brookrege-firewall apply && echo "  ✓ firewall re-applied"
fi
echo "✓ Cloudflare ranges synced to $CF_DIR"
